### ISSUE TITLE
library.cpp:1:10: fatal error: 'stdio.h' file not found

### ISSUE THREAD

**Issue by elvin-du** [PetterS/clang-wasm#6]
run `make`， following error occurs：

```
library.cpp:1:10: fatal error: 'stdio.h' file not found
```

**Comment by mingodad** [comment]
It seems that this https://github.com/PetterS/clang-wasm/pull/8 solve it and also compile with new versions of clang/llvm

**Comment by PetterS** [comment]
Now fixed.
